"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ltap6wjx@yj%3y9c&4=@43a7%)x-4lu-xhbz!7%1y7r7pj(m0b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #myapps
    'jwt_api',
    'rest_framework',
    'rest_framework_simplejwt',
    'djangosaml2'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'jwt_api',
        'USER': 'root',
        'PASSWORD':'root',
        'HOST':'localhost',
        'PORT':3306
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#jwt configurations

REST_FRAMEWORK = {
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME" : timedelta(minutes=5),
    "RERESH_TOKEN_LIFETIME" : timedelta(days=1),
}

#SAML configurations

# SAML_SETTINGS = {
#     'strict' : True,
#     'debug' : False,
#     'sp' : {
#         'entityId' : 'http://127.0.0.1:8000/metadata',
#         'assertionConsumerService' : {
#             'url' : 'http://127.0.0.1:8000/saml/callback',
#             'binding': 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',          
#             },
#         'singleLogoutService' : {
#             'url' : 'http://127.0.0.1:8000/saml/logout',
#             'binding': 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
#         },
#         'NameIDFormat': 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified',
#         'x509cert': '',
#         'privateKey': '',
#     },
#     'idp' : 
# }


SAML_SETTINGS = {
    'SP_ENTITY_ID': 'http://localhost:8000/sso/acs/',  
    'ACS_URL': 'http://localhost:8000/sso/acs/',  
    'IDP_ENTITY_ID': 'https://idp.example.com/saml',  
    'IDP_SSO_URL': 'https://idp.example.com/sso',  
    'IDP_PUBLIC_CERT': '/path/to/idp-public-cert.pem',  
    'SAML_METADATA_URL': 'https://idp.example.com/metadata',  
}
AUTH_USER_MODEL = "jwt_api.CustomUser"




